In [ ]:
#Agenda

What is Machine Learning?
What are the two main categories of Machine Learning?
What are some examples of Machine Learning?
How does Machine Learning "work"?

In [ ]:
What is Machine Learning?

One definition: "Machine Learning is the semi-automated extraction of knowledge from data"

Knowledge from data: Starts with a question that might be answerable using data
Automated extraction: A computer provides the insight
Semi-automated: Requires many smart decisions by a human

In [ ]:
What are the two main categories of Machine Learning?

Supervised learning: Making predictions using data

Unsupervised learning: Extracting structure from data


In [ ]:
How does Machine Learning "work"?
High-level steps of supervised learning:

First, train a Machine Learning model using labeled data

"Labeled data" has been labeled with the outcome
"Machine Learning model" learns the relationship between the attributes of the data and its outcome
Then, make predictions on new data for which the label is unknown

In [1]:
from sklearn.datasets import load_iris

In [6]:
from IPython.display import IFrame
IFrame('https://www.dataschool.io/files/iris.txt', width=300, height=200)

In [8]:
iris = load_iris()
type(iris)

sklearn.utils._bunch.Bunch

In [9]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
# print the names of the four features
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
# print integers representing the species of each observation
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [10]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [ ]:
#Requirements for working with data in scikit-learn
Features and response are separate objects
Features should always be numeric, and response should be numeric for regression problems
Features and response should be NumPy arrays
Features and response should have specific shapes

In [11]:
#supervised - Classification & regression algorithmns

# check the types of the features and response
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
print(iris.data.shape)

(150, 4)


In [13]:
print(iris.target.shape)

(150,)


In [14]:
# store feature matrix in "X"
X = iris.data

# store response vector in "y"
y = iris.target

In [15]:
# print the shapes of X and y
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [16]:
#Step 1: Import the class you plan to use

from sklearn.neighbors import KNeighborsClassifier

In [17]:
#Step 2: "Instantiate" the "estimator"

#"Estimator" is scikit-learn's term for model
#"Instantiate" means "make an instance of"

knn = KNeighborsClassifier(n_neighbors=1)

In [18]:
print(knn)

KNeighborsClassifier(n_neighbors=1)


In [19]:
#Step 3: Fit the model with data (aka "model training")

#Model is learning the relationship between X and y
#Occurs in-place

knn.fit(X, y)

KNeighborsClassifier(n_neighbors=1)

In [20]:
#Step 4: Predict the response for a new observation

#New observations are called "out-of-sample" data
#Uses the information it learned during the model training process

knn.predict([[3, 5, 4, 2]])

array([2])

In [21]:
#can predit for multiple observations

X_new = [[3, 5, 4, 2], [5, 4, 3, 2]]
knn.predict(X_new)

array([2, 1])

In [22]:
#using different value for K

# instantiate the model (using the value K=5)
knn = KNeighborsClassifier(n_neighbors=5)

# fit the model with data
knn.fit(X, y)

# predict the response for new observations
knn.predict(X_new)

array([1, 1])

In [23]:
#use different classification model

# import the class
from sklearn.linear_model import LogisticRegression

# instantiate the model
logreg = LogisticRegression(solver='liblinear')

# fit the model with data
logreg.fit(X, y)

# predict the response for new observations
logreg.predict(X_new)

array([2, 0])